scripte utf-8 
set shell=/bin/bash
set nocompatible autoindent laststatus=2 relativenumber nu smartcase nopaste nowrap expandtab hidden
set noswapfile nobackup nowritebackup shiftwidth=4 softtabstop=4 tabstop=4 is ttimeoutlen=100   " ttimeout to stop esc hanging on : commands
set backspace=indent,eol,start hlsearch path+=** wildmenu autoread undofile undodir=~/.vim/undodir 
set grepprg=rg\ --vimgrep|set complete= |set grepformat^=%f:%l:%c:%m|set viminfo='50,<5000,s100  " increase vim register limit so that we can copy more data between instances 
au FileType python setlocal noexpandtab softtabstop=4 tabstop=4 shiftwidth=4
au FileType c setlocal noexpandtab softtabstop=2 tabstop=2 shiftwidth=2
let g:netrw_banner = 0 | let mapleader = "\<Space>"
filetype indent on | syntax on | filetype plugin on
au FileType yaml setlocal ai< ci< si< 
set rtp+=~/.nix-profile/bin/
ino jk <esc>| nn K <nop>| nn U <nop> | nn Q <nop>
com! Qa qa | com! QA qa | com! Q q|                                                             " typo friendly commands. 'w' commands are separate lines (not |) Parser treats | as filename
com! WQ wq
com! Wq wq
com! W w
com! E Explore|                                                                                 " Enforce Explore shorthand command (in case of ambiguity eg. Emmet)
vm < <gv | vm > >gv|                                                                            " visual mode indenting
vn <leader>s "vy :%s/<C-R>v//g<Left><Left>|                                                     " search visual
vn <leader>S "vy :%s//<C-R>v/g<C-b><Right><Right><Right>|                                       " search visual
nn <leader>s :%sno/<C-R><C-W>//g<Left><Left>|                                                   " search
nn <leader>S :%sno//<C-R><C-W>/g<C-b><Right><Right><Right><Right><Right>|                       " search 
nn <leader>z :noh<CR>                                                                           " search  highlight
nn <leader>0 :set scroll=0<CR>                                                                  " scroll reset
vn  <C-y> "*y                                                                                   " yank into clipboard 
vn  <C-p> "*p                                                                                   " paste from clipboard 
nn  <C-j> :m .+1<CR>==| nn <C-k> :m .-2<CR>==|                                                  " shuffle line one up or down Normal mode
ino <C-j> <Esc>:m .+1<CR>==gi| ino <C-k> <Esc>:m .-2<CR>==gi|                                   " shuffle line one up or down Insert mode
vn  <C-j> :m '>+1<CR>gv=gv| vn <C-k> :m '<-2<CR>gv=gv|                                          " shuffle line one up or down Visual mode
nn <C-w>v :echo "disabled"<CR> | nn <C-w>s :echo "disabled"<CR>
nor <leader>; :call nerdcommenter#Comment(1, 'toggle')<CR>|                                     " NERD commenter installed in setup.sh
let g:fzf_vim = {}
let g:fzf_vim.preview_window = ['right,50%,<50(hidden)', 'ctrl-/']
nn <leader><leader> :Files<CR>|                                                                 " FZF stuff
nn <leader>/ :Rg<CR>|
nn <leader>. :BLines<CR>|
nn <leader>m :History<CR>|
cno <C-a> <Home>
cno <C-e> <End>
fu! GitRoot()
  let r = trim(system('git rev-parse --show-toplevel 2>/dev/null')) | return v:shell_error ? '' : r
endf
fu! GitPath()
  let r = GitRoot() | return '/tmp/'.(r == '' ? 'global' : trim(system('echo '.r.' | md5')))
endf
fu! OnBlur()
  let f = GitPath()
  exe 'wviminfo! '.f.'.viminfo'
  if @" != '' | call writefile([@"], '/tmp/vimcopy.txt') | endif
  call writefile([expand('%:p').':'.line('.')], f.'.file')
endf
fu! Restore()
  let f = GitPath()
  if !filereadable(f.'.file') | return | endif
  let b = split(get(readfile(f.'.file'), 0, ''), ':')
  if len(b) > 1 | exe 'e '.b[0] | call cursor(b[1], 0) | endif
  sil! exe 'rviminfo! '.f.'.viminfo'
endf
fu! RestoreCopy()
  sleep 50m
  let f = '/tmp/vimcopy.txt'
  if filereadable(f) | let @" = join(readfile(f), "\n") | endif
endf
let a ='`1234567890-= ~!@#$%^&*()_+ qwertyuiop[]  QWERTYUIOP{} asdfghjkl;''\ ASDFGHJKL:"| zxcvbnm,./    ZXCVBNM<>?   '
let b ='˜˘¨⁼⌜´˝7∞¯•÷× ¬⎉⚇⍟◶⊘⎊⍎⍕⟨⟩√⋆ ⌽𝕨∊↑∧◁⊔⊏⊐π←→  ↙𝕎⍷𝕣⍋◀U⊑⊒⍳⊣⊢ ⍉𝕤↕𝕗𝕘⊸∘○⟜⋄↩\  ↖𝕊D𝔽𝔾«↺⌾»·˙| ⥊𝕩↓∨⌊□≡∾≍≠    ⋈𝕏C⍒⌈■≢≤≥⇐   '
let c ='AdDESsTtoONkyRrQqZij0123)!@#*-_|'
let d ="∀ΔΔ∃■□◀◁○⬤ℕ✓☺ℝ↺▫▯Σᵢⱼ₀₁₂₃⁰¹²³꘎ⁿₙ|" | " g used for •Show
let[a,b]=map([a,b],{i,x->split(x,'\zs *')}) | let a+=['<space>']|let b+=['‿']
for l in ['i','c']|for i in range(len(a))|exe escape(l.'no'.'\'.a[i].' '.b[i],'|')|endfor|endfor
for l in ['i','c']|for i in range(len(c))|exe escape(l.'no'.'|'.c[i].' '.matchstr(d,'.',0,i+1),'|')|endfor|endfor
unl a b c d l i
nn <leader>r :source $MYVIMRC<CR>
nn <leader>G mm:%s/•Show //g<CR>`m
ino <Bar>g •Show 
vn <leader>G :s/\%V•Show //gi<CR><ESC>
nn <leader>g i•Show <Esc>
vn <leader>g I•Show <Esc>
fu! FmtBQN(l)
  let c=join(getline(1, '$'), "\n")
  let o=system('bqf', c)
  call setline(1, split(o, "\n",1))
endf
nor <leader>ff :call FmtBQN()<CR>
fu! ExpBQN(l)
  echo system('bqe ' . '"'.escape(a:l, "`\"'").'"')
endf
vn <leader>e "vy :call ExpBQN(@v)<cr>
nn <leader>e :call ExpBQN(getline('.'))<cr>
augroup Vimrc
  au!
  au BufRead,BufNewFile * if getline(1) =~ '^#!.*bqn$' | setf bqn | endif
  au BufRead,BufNewFile *.bqn setf bqn
  au BufNewFile,BufRead *.arr set ft=bqn
  au FileType bqn syn match bqncom "#.*$"
  au FileType bqn hi link bqncom comment
  au FileType bqn setlocal softtabstop=2 tabstop=2 shiftwidth=2 expandtab cms=#%s
  au InsertLeave,TextChanged    * if GitRoot() != '' | sil! w | endif
  au VimEnter                   * let r=GitRoot() | if r!='' | exe 'cd' r | endif
  au VimEnter                   * nested call RestoreCopy()
  au TextYankPost,VimLeave,FocusLost * call OnBlur()
  au FocusGained                * call RestoreCopy()
  au VimEnter,FocusGained,BufEnter * let @/ = ''
augroup END
