if [ -e '/nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh' ]; then
  . '/nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh'
fi

git_branch() {
    git branch 2>/dev/null | grep '^*' | colrm 1 2
}

EDITOR='vim'
VISUAL='vim'
alias ls='ls -G'
alias gti=git

PROMPT="%F{red}%n%F{blue} %1d%f %F{cyan}$(git_branch)%f %F{blue}→%f "

bindkey "^[[1;5C" forward-word
bindkey "^[[1;5D" backward-word
bindkey ";6;13~" forward-word
bindkey ";5;13~" backward-word
