
(load "~/.emacs.d/config/init.el")
(load "~/.emacs.d/config/packages.el")
(load "~/.emacs.d/config/ui.el")

(load "~/.emacs.d/config/packages/autocomplete.el")
(load "~/.emacs.d/config/packages/cider.el")
(load "~/.emacs.d/config/packages/dired-mode.el")
(load "~/.emacs.d/config/packages/emmet-mode.el")
(load "~/.emacs.d/config/packages/eshell-mode.el")
(load "~/.emacs.d/config/packages/evil-leader-mode.el")
(load "~/.emacs.d/config/packages/evil-mode.el")
(load "~/.emacs.d/config/packages/evil-surround-mode.el")
(load "~/.emacs.d/config/packages/flymake-mode.el")
(load "~/.emacs.d/config/packages/haskell-mode.el")
(load "~/.emacs.d/config/packages/helm.el")
(load "~/.emacs.d/config/packages/linum.el")
(load "~/.emacs.d/config/packages/magit.el")
(load "~/.emacs.d/config/packages/powerline.el")
(load "~/.emacs.d/config/packages/projectile.el")
